name: Node.js CI

on:
  push:
    branches: [QA-(testing)]  # Ejecuta los tests en cada push a la rama "QA-(testing)"
  pull_request:
    branches: [main]  # Ejecuta los tests en cada pull request a la rama "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PostgreSQL Client
        run: sudo apt-get install -y postgresql-client
      
      - name: Display connection info
        run: |
          echo "Host: ${{ secrets.POSTGRES_HOST }}"
          echo "User: ${{ secrets.POSTGRES_USER }}"
          echo "Database: ${{ secrets.POSTGRES_DATABASE }}"


      - run: npm install
      - run: npm test
        env:  
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
          POSTGRES_URL_NO_SSL: ${{ secrets.POSTGRES_URL_NO_SSL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
