name: Node.js CI

on:
  push:
    branches: [main]  # Ejecuta los tests en cada push a la rama "main"
  pull_request:
    branches: [main]  # Ejecuta los tests en cada pull request a la rama "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # Puedes especificar la versión de Node.js

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
